### ISSUE TITLE
Problems with @font-face

### ISSUE THREAD

**Issue by PetersOtto** [retext-project/retext#465]
I am using:
Ubuntu 16.04
ReText 7.0.4 (mit PyMarkups 3.0.0)
PyQtWebEngine from PyPI

The last hours I tried to set fonts with @font-face in the StyleSheet file (styleSheet=path/file.css). However it don't work. When I use export to pdf, reText use an other font.

The path to the font is right and the StyleSheet is working.

Do you have any idea?

**Comment by mitya57** [comment]
I tried to reproduce it, but it works for me. I have put in my `main.css` the following content:
```css
@font-face {
  font-family: 'Indie Flower';
  font-style: normal;
  font-weight: 400;
  src: url('file:///home/dmitry/upstream/retext/indie-flower-v10-latin-regular.woff2') format('woff2')
}

body {
  font-family: 'Indie Flower';
}
```

Then I have specified this in `ReText.conf`:
```ini
[General]
styleSheet=/home/dmitry/upstream/retext/main.css
useWebEngine=true
```

Then I open `README.md` in ReText and it uses the font as expected in both preview and PDF export:
![Screenshot](https://user-images.githubusercontent.com/1381584/60249193-f7397900-98cc-11e9-9dad-c9d08f00b03a.png)

Please make sure that:

- The checkbox “Use WebEngine (Chromium) renderer” is selected in the Edit menu;
- You specify absolute URL to the font in your CSS file;
- You have a `body` or equivalent section in the CSS file;
- You specify absolute path to the CSS file in the configuration file.

Also, there is an easier approach to the same problem. Why not just use the “Edit → Change preview font” menu item?
