### ISSUE TITLE
How to change background & text color?

### ISSUE THREAD

**Issue by eclecticpassions** [retext-project/retext#666]
I am able to change the font and size in the Menu > Edit > Change Editor Font and Preview Font, but I can't change the colour of the font and also no option to change the background colour of both the markdown view or preview section. 

I tried making a custom.css and adding it to Preferences > Interface > Stylesheet file using CSS selectors mentioned [here](https://doc.qt.io/qt-6/stylesheet-reference.html), and restarted but it doesn't apply.

```css
QTextEdit {
  color: #cecece;
  background-color: #373737; 
}
```

I also don't know how to set up the config file. Do I just make a .md file and place it in: `/~/Documents/Retext_venv/lib/python3.13/site-packages/ReText/config.md`? Can there be some example of the syntax/format? For example: `[editorFont] = "Arial"`? 

I tried searching in the issues but I couldn't find any help there... sorry for the noob questions.

I am on macOS 15.5, installed with pip3 in a venv. Thanks!

**Comment by eclecticpassions** [comment]
Thanks @mitya57 for clarifying it a bit... I didn't know I could click that link and use the configuration.md parameters there. But I couldn't change the background and text colour of the left and right panels still. I tried a few css selectors like this in my appStyleSheet custom.css:
```css
QLineEdit {
  color: #19d71c;/*input text of preferences*/
  background: #af1010; /*input box of preferences*/
  selection-background-color: #7234de; /*input text selection of preferences*/
}


QMainWindow {
  background-color: #d719b1; /*border colour of main window*/
}
```
and the changes are in the preference window and the border of the main window (where the two panels are):

![Image](https://github.com/user-attachments/assets/d24e0989-b963-4dfe-b51c-ac5d1750598b)

My config file (ReText.ini) is like this now (I just added the last line which is the appStyleSheet you instructed): 
```ini
[General]
autoSave=true
defaultPreviewState=live-preview
editorFont="MesloLGS NF,17,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
font="Inter,17,-1,5,300,0,0,0,0,0,0,0,0,0,0,1,Light"
saveWindowGeometry=true
styleSheet=/Users/path/Retext_custom.css
tabBarAutoHide=true
windowTitleFullPath=true
appStyleSheet=/Users/path/Retext_custom.css
```
I noticed there was already a `styleSheet` line there, which links to the same custom.css. Should I comment that out?

Thanks a million!
